# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-31 11:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import django_contact_forms.models.contact_form_attachment
import django_contact_forms.utils.encrypted_field


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_contact_forms", "0001_initial"),
        ("django_contact_forms", "0002_contactform_code_contactform_type"),
        ("django_contact_forms", "0003_formnotificationconfig"),
        ("django_contact_forms", "0004_contactform_status"),
        ("django_contact_forms", "0005_bookings_leads_offline_conversions"),
        ("django_contact_forms", "0006_lead_status_contactdate_index"),
        ("django_contact_forms", "0007_leadcreationrule"),
        ("django_contact_forms", "0008_alter_bookingconfig_provider"),
        ("django_contact_forms", "0009_alter_booking_provider"),
        ("django_contact_forms", "0010_bookingconfig_fomo_blackout_full_days_and_more"),
        ("django_contact_forms", "0011_formtype"),
        ("django_contact_forms", "0012_formnotificationconfig_send_client_copy"),
        ("django_contact_forms", "0013_seed_default_form_type"),
        ("django_contact_forms", "0014_alter_bookingtimewindow_id"),
    ]

    # Data payloads from the replaced chain are intentionally omitted — both are
    # upgrade-only backfills that iterate over pre-existing rows, so on a fresh
    # database they are no-ops (and on an upgraded database this squash is
    # skipped entirely via `replaces`):
    #   - 0010: one default BookingTimeWindow per existing BookingConfig
    #   - 0013: default FormType for channels with an empty catalog
    # Cross-app dependency targets the regional squash, not its leaf — depending
    # on a later leaf breaks upgrades with InconsistentMigrationHistory.
    dependencies = [
        ("django_regional", "0001_squashed_0006_country_default_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormsSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bookings_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable the public booking endpoint and BookingConfig per-channel rows.",
                    ),
                ),
                (
                    "google_ads_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable Lead status → Google Ads offline conversion enqueue + worker."
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Forms settings",
                "verbose_name_plural": "Contact Forms settings",
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("label", models.CharField(default="", max_length=128, unique=True)),
                ("admin_email", models.EmailField(default="email_administratora_fromularzu@test.pl", max_length=254)),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_language_forms",
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "channels",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="BookingConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("google_calendar", "Google Calendar"), ("local", "Local (no external calendar)")],
                        default="google_calendar",
                        help_text="Calendar backend. 'google_calendar' requires the [bookings] extra + service-account credentials; 'local' is DB-only and needs no external setup. See docs/volkanos/modules/contact-forms/bookings.",
                        max_length=32,
                    ),
                ),
                (
                    "service_account_credentials_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Absolute path inside the container to the service-account JSON key. Validated against CONTACT_FORMS_CREDENTIALS_DIR (default /app/credentials/) — must be a real .json file under that directory, no symlinks.",
                        max_length=512,
                    ),
                ),
                (
                    "impersonate_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email of the real user the service account acts as (events created on their primary).",
                        max_length=254,
                    ),
                ),
                (
                    "calendar_id",
                    models.CharField(
                        blank=True,
                        default="primary",
                        help_text="Shared calendar ID for free-busy queries; 'primary' for impersonated user only.",
                        max_length=255,
                    ),
                ),
                ("slot_duration_minutes", models.PositiveIntegerField(default=30)),
                ("days_ahead", models.PositiveIntegerField(default=14)),
                ("weekdays_only", models.BooleanField(default=True)),
                ("timezone", models.CharField(default="Europe/Warsaw", max_length=64)),
                (
                    "event_summary_template",
                    models.CharField(
                        default="Booking - {name}",
                        help_text="Use {name} as a placeholder for the booker's name.",
                        max_length=255,
                    ),
                ),
                (
                    "fomo_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Master toggle for synthetic busy slots ('fake-booked' time blocks shown to visitors to combat empty-calendar deterrence). Off = exact real availability is shown.",
                    ),
                ),
                (
                    "fomo_intensity",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="0-100. Apparent fill-up perception. 0 = off, 50 = balanced (~50% peak slots fake-busy), 80 = aggressive. Values >80 are clamped per-day to avoid 'fully booked' deterrence (visitors abandon when they see no openings).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "fomo_blackout_full_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Max full-day blackouts within the visible window (today and tomorrow are always excluded so 'fresh availability' urgency works). 0 = no blackouts.",
                        validators=[django.core.validators.MaxValueValidator(3)],
                    ),
                ),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_config",
                        to="django_contact_forms.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking config",
                "verbose_name_plural": "Booking configs",
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(editable=False, max_length=128)),
                (
                    "scope",
                    models.CharField(
                        choices=[("contact_form", "Contact form"), ("booking", "Booking")],
                        default="contact_form",
                        help_text="What endpoints this key may call. Existing keys default to 'contact_form'.",
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="django_contact_forms.channel"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(default=None, max_length=12, primary_key=True, serialize=False, unique=True)),
                ("slug", models.CharField(blank=True, max_length=256, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("body", models.JSONField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=256, null=True)),
                ("code", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("todo", "To Do"), ("in_progress", "In Progress"), ("done", "Done")],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contact_forms.channel"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "contact_forms",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="ContactFormAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="It will automatically be filled in with the file name when saving",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        storage=django_contact_forms.models.contact_form_attachment.contact_form_storage,
                        upload_to=django_contact_forms.models.contact_form_attachment.contact_form_attachment_directory_path,
                    ),
                ),
                (
                    "contact_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="django_contact_forms.contactform"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Channel-level enable. Must also satisfy the global ContactFormsSettings.google_ads_enabled toggle.",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google Ads account ID, digits only (e.g. 8323936346).",
                        max_length=16,
                    ),
                ),
                (
                    "login_customer_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional MCC ID when accessing via manager account.",
                        max_length=16,
                    ),
                ),
                (
                    "oauth_refresh_token",
                    django_contact_forms.utils.encrypted_field.EncryptedTextField(
                        blank=True, default="", help_text="OAuth2 refresh token (encrypted at rest)."
                    ),
                ),
                ("default_currency_code", models.CharField(default="EUR", max_length=3)),
                ("meeting_booked_action_id", models.CharField(blank=True, default="", max_length=32)),
                ("qualified_lead_action_id", models.CharField(blank=True, default="", max_length=32)),
                ("won_deal_action_id", models.CharField(blank=True, default="", max_length=32)),
                ("meeting_booked_value", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("qualified_lead_value", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_config",
                        to="django_contact_forms.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Ads config",
                "verbose_name_plural": "Google Ads configs",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendar"),
                            ("form", "Contact form"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=16,
                    ),
                ),
                ("contact_date", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("message", models.TextField(blank=True, default="")),
                ("gclid", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                (
                    "hashed_email",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 hex of lower-cased email (enhanced fallback).",
                        max_length=64,
                    ),
                ),
                (
                    "attribution_method",
                    models.CharField(
                        choices=[
                            ("gclid", "Google Click ID"),
                            ("enhanced", "Enhanced (hashed email)"),
                            ("time_proximity", "Time-based proximity"),
                            ("manual", "Manual"),
                            ("unattributed", "Unattributed"),
                        ],
                        default="unattributed",
                        max_length=16,
                    ),
                ),
                ("campaign_name", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("medium", models.CharField(blank=True, default="", max_length=255)),
                ("landing_page", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("unqualified", "Unqualified"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
                ("deal_value", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("ads_conversion_imported", models.BooleanField(default=False)),
                ("ads_imported_at", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "contact_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="django_contact_forms.contactform",
                    ),
                ),
            ],
            options={
                "ordering": ["-contact_date"],
            },
        ),
        migrations.CreateModel(
            name="LeadCreationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("form_type", models.CharField(blank=True, default="", max_length=256)),
                ("slug", models.CharField(blank=True, default="", max_length=256)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendar"),
                            ("form", "Contact form"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("other", "Other"),
                        ],
                        default="form",
                        help_text="Value written to Lead.source_type when this rule fires.",
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contact_forms.channel"),
                ),
            ],
            options={
                "verbose_name": "lead creation rule",
                "verbose_name_plural": "lead creation rules",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="OfflineConversionQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "conversion_action_id",
                    models.CharField(help_text="Google Ads conversion action ID (digits only).", max_length=32),
                ),
                (
                    "conversion_action_label",
                    models.CharField(
                        help_text="Human label for admin (e.g. 'Meeting Booked', 'Won Deal').", max_length=64
                    ),
                ),
                ("conversion_time", models.DateTimeField()),
                ("conversion_value", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency_code", models.CharField(default="EUR", max_length=3)),
                (
                    "conversion_environment",
                    models.CharField(choices=[("WEB", "Web"), ("APP", "App")], default="WEB", max_length=8),
                ),
                ("gclid", models.CharField(blank=True, default="", max_length=255)),
                ("hashed_email", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_conversions",
                        to="django_contact_forms.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingTimeWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField(default=0, help_text="Sort order for admin display.")),
                ("start_time", models.TimeField(help_text="Window start (inclusive), e.g., 10:00.")),
                ("end_time", models.TimeField(help_text="Window end (exclusive), e.g., 12:30.")),
                (
                    "booking_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_windows",
                        to="django_contact_forms.bookingconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["booking_config", "order", "start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="bookingtimewindow_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("google_calendar", "Google Calendar"), ("local", "Local (no external calendar)")],
                        default="google_calendar",
                        max_length=32,
                    ),
                ),
                ("calendar_event_id", models.CharField(db_index=True, max_length=255)),
                ("meet_link", models.URLField(blank=True, default="")),
                ("meeting_start", models.DateTimeField()),
                ("meeting_end", models.DateTimeField()),
                ("timezone", models.CharField(max_length=64)),
                (
                    "contact_form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="django_contact_forms.contactform",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["meeting_start"], name="django_cont_meeting_6acd2b_idx")],
            },
        ),
        migrations.CreateModel(
            name="FormNotificationConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("form_type", models.CharField(blank=True, default="", max_length=256)),
                ("slug", models.CharField(blank=True, default="", max_length=256)),
                ("send_email", models.BooleanField(default=True)),
                (
                    "send_client_copy",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the submitter receives a copy email (gated additionally by body.send_copy).",
                    ),
                ),
                ("recipient_email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_contact_forms.channel"),
                ),
            ],
            options={
                "verbose_name": "form notification config",
                "verbose_name_plural": "form notification configs",
                "ordering": [],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "form_type", "slug"), name="unique_channel_form_type_slug"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FormType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=256)),
                ("label", models.CharField(blank=True, default="", max_length=256)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used when a submission carries no type or an unknown one. One per channel.",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_types",
                        to="django_contact_forms.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "form type",
                "verbose_name_plural": "form types",
                "ordering": [],
                "constraints": [
                    models.UniqueConstraint(fields=("channel", "code"), name="unique_channel_form_type_code"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("channel",),
                        name="unique_default_form_type_per_channel",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["-contact_date"], name="django_cont_contact_5107f3_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status", "-contact_date"], name="django_cont_status_1bac0a_idx"),
        ),
        migrations.AddConstraint(
            model_name="leadcreationrule",
            constraint=models.UniqueConstraint(
                fields=("channel", "form_type", "slug"), name="unique_lead_rule_channel_type_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="offlineconversionqueue",
            index=models.Index(fields=["-created_at"], name="django_cont_created_8240f0_idx"),
        ),
        migrations.AddConstraint(
            model_name="offlineconversionqueue",
            constraint=models.UniqueConstraint(
                fields=("lead", "conversion_action_id"), name="uniq_lead_conversion_action"
            ),
        ),
    ]
