# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

from datetime import UTC, datetime, time, timedelta

import factory
from django_regional.models import Language

from django_contact_forms.models import (
    APIKey,
    Booking,
    BookingConfig,
    BookingTimeWindow,
    Channel,
    ContactForm,
    ContactFormAttachment,
    ContactFormsSettings,
    FormNotificationConfig,
    FormType,
    GoogleAdsConfig,
    Lead,
    LeadCreationRule,
)
from tests.conftest import import_keys_into_access


class LanguageFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Language
        django_get_or_create = ("iso2",)

    iso2 = "en"
    iso3 = "eng"
    name_en = "English"
    name_pl = "Angielski"
    name_source = "English"


class ChannelFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Channel

    idx = factory.Sequence(lambda n: f"channel-{n}")
    label = factory.Sequence(lambda n: f"Channel {n}")
    admin_email = factory.LazyAttribute(lambda o: f"admin-{o.idx}@example.com")
    default_language = factory.SubFactory(LanguageFactory)


class APIKeyFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = APIKey

    channel = factory.SubFactory(ChannelFactory)
    # key auto-generated by APIKey.save()

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        key = super()._create(model_class, *args, **kwargs)
        import_keys_into_access()
        return key


class ContactFormFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = ContactForm

    email = factory.Sequence(lambda n: f"user{n}@example.com")
    channel = factory.SubFactory(ChannelFactory)
    slug = "contact-us"
    type = "general"
    body = {"message": "Test message"}


class ContactFormAttachmentFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = ContactFormAttachment

    contact_form = factory.SubFactory(ContactFormFactory)
    name = factory.Sequence(lambda n: f"file{n}.txt")
    attachment = factory.django.FileField(filename="test.txt", data=b"test content")


class FormNotificationConfigFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = FormNotificationConfig

    channel = factory.SubFactory(ChannelFactory)
    form_type = ""
    slug = ""
    send_email = True
    recipient_email = ""


class FormTypeFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = FormType

    channel = factory.SubFactory(ChannelFactory)
    code = factory.Sequence(lambda n: f"type-{n}")
    label = factory.LazyAttribute(lambda o: o.code.title())
    is_default = False


class BookingConfigFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = BookingConfig

    channel = factory.SubFactory(ChannelFactory)
    enabled = True
    service_account_credentials_path = "/app/credentials/sa.json"
    impersonate_email = factory.LazyAttribute(lambda o: f"bookings-{o.channel.idx}@example.com")
    calendar_id = "primary"
    timezone = "Europe/Warsaw"

    @factory.post_generation
    def time_windows(obj, create, extracted, **kwargs):
        """Auto-create one default 9:00-17:00 window unless `time_windows=[...]` is passed.

        Tests that need different windows pass: ``BookingConfigFactory(time_windows=[
            {"start_time": time(10, 0), "end_time": time(12, 30)},
            {"start_time": time(16, 0), "end_time": time(17, 0)},
        ])``.
        """
        if not create:
            return
        if extracted:
            for i, w in enumerate(extracted):
                BookingTimeWindow.objects.create(
                    booking_config=obj, order=w.get("order", i), **{k: v for k, v in w.items() if k != "order"}
                )
        else:
            BookingTimeWindow.objects.create(booking_config=obj, order=0, start_time=time(9, 0), end_time=time(17, 0))


class BookingTimeWindowFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = BookingTimeWindow

    booking_config = factory.SubFactory(BookingConfigFactory)
    order = 0
    start_time = time(9, 0)
    end_time = time(17, 0)


class GoogleAdsConfigFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = GoogleAdsConfig

    channel = factory.SubFactory(ChannelFactory)
    enabled = True
    customer_id = factory.Sequence(lambda n: str(1000000000 + n))
    oauth_refresh_token = "test-refresh-token"
    meeting_booked_action_id = "9000000001"
    qualified_lead_action_id = "9000000002"
    won_deal_action_id = "9000000003"
    meeting_booked_value = 200
    qualified_lead_value = 500


class LeadFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Lead

    contact_form = factory.SubFactory(ContactFormFactory)
    name = factory.Sequence(lambda n: f"Lead {n}")
    email = factory.Sequence(lambda n: f"lead{n}@example.com")
    source_type = Lead.SourceType.FORM


class LeadCreationRuleFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = LeadCreationRule

    channel = factory.SubFactory(ChannelFactory)
    form_type = ""
    slug = ""
    enabled = True
    source_type = Lead.SourceType.FORM


class BookingFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Booking

    contact_form = factory.SubFactory(ContactFormFactory)
    provider = "google_calendar"
    calendar_event_id = factory.Sequence(lambda n: f"evt-{n}")
    meet_link = factory.Sequence(lambda n: f"https://meet.google.com/abc-def-{n:03d}")
    meeting_start = factory.LazyFunction(lambda: datetime.now(UTC) + timedelta(days=1))
    meeting_end = factory.LazyAttribute(lambda o: o.meeting_start + timedelta(minutes=30))
    timezone = "Europe/Warsaw"


def enable_global_settings(*, bookings: bool = False, google_ads: bool = False) -> ContactFormsSettings:
    s = ContactFormsSettings.load()
    s.bookings_enabled = bookings
    s.google_ads_enabled = google_ads
    s.save()
    return s
